### ISSUE TITLE
Publish latest segment_analytics_plugin_idfa

### ISSUE THREAD

**Issue by qirong-zhang-ext** [segmentio/analytics_flutter#141]
Hi Segment team,

I can see there is a fix(#59) for segment_analytics_plugin_idfa(1.0.0), but seems you forgot to publish latest version for new fix(1.0.1), now we can only import plugin by this:
```yaml
segment_analytics_plugin_idfa:
  git:
    url: https://github.com/segmentio/analytics_flutter
    ref: ae885ab3fa5aaf6a81c27703bac8d9c0edaa40b6
    path: packages/plugins/plugin_idfa
```

Since branch v1.0 does not include this fix as well, but for Android side works well
```yaml
segment_analytics_plugin_advertising_id: ^1.0.0
```

Could you please publish a new version for segment_analytics_plugin_idfa to include above fix, so that we can import it with version control.
Thanks.
