### ISSUE TITLE
Is there a way to track a `Push Notification Received` event?

### ISSUE THREAD

**Issue by omarhussein-ava** [segmentio/analytics_flutter#57]
As the question on the title says, we want to track this event using the Segments SDK, how to activate it? 

We're using Flutter 3.19.6 and the following dependencies:

```yaml
  analytics:
    git:
      url: https://github.com/segmentio/analytics_flutter
      ref: main
      path: packages/core
  analytics_plugin_firebase:
    git:
      url: https://github.com/segmentio/analytics_flutter
      ref: main
      path: packages/plugins/plugin_firebase
```
